### ISSUE TITLE
How do you set this up?

### ISSUE THREAD

**Issue by kyle-charlton** [norcross/reaktiv-remote-repo#2]
Hi,
I just this plugin from http://halfelf.org/2014/self-update-your-plugins/ and so far it looks pretty great.
How do you go about setting everything up?

## Updater Class
There are a couple variables here to be set, are the ones below the only ones that need to be set or are there others?

What exactly do I put in some of these fields?
```php
    private $api_url	= '';
	private $api_data	= array();
	private $name		= '';
	private $unique	= '';
	private $slug		= '';
```

## Plugin
I'm guessing the below codes gets added to the plugin itself do I only have to fill in the DEFINE items?
```php
// set our defined items
DEFINE( 'RKV_UPDATE_URL', '' );
DEFINE( 'RKV_ITEM', '' );
DEFINE( 'RKV_VERS', '' );

// load the class if we haven't aready
if ( ! class_exists( 'RKV_Remote_Updater' ) ) {
	include( 'RKV_Remote_Updater.php' );
}


add_action ( 'admin_init', 'rkv_auto_updater' );
/**
 * load our auto updater function
 * @return [type] [description]
 */
function rkv_auto_updater() {
	// Setup the updater
	$updater = new RKV_Remote_Updater( RKV_UPDATE_URL, __FILE__, array(
		'item'		=> RKV_ITEM,
		'version'   => RKV_VERS,
		)
	);
}
```

**Comment by norcross** [comment]
I've updated the readme with some example code. You don't touch the updater class itself at all.

**Comment by kyle-charlton** [comment]
Awesome! I'll have to give it a try.
Thanks!
