### ISSUE TITLE
Repo Configuration

### ISSUE THREAD

**Issue by jamesckemp** [norcross/reaktiv-remote-repo#4]
Hi Andrew,

This plugin looks ideal. The only thing I don't quite understand is the repo side of things; primarily the repo URL and the Unique Key.
- I have a few plugins, do I need to set up a separate, self-hosted, repo with only the update zip files for each plugin?
- Could those repos be accessed publicly?
- How/where is unique key generated?
- Does the repo URL have to end with update, or is update an example repo location?

Hope this makes sense!

Thanks,
James

**Comment by norcross** [comment]
* one repo will handle it all.
each item is a post (the `repo-items` custom post type to be specific). the unique key will be generated when it's saved.

**Comment by norcross** [comment]
- one repo will handle it all. each item is a post (the `repo-items` custom post type to be specific).
- the unique key will be generated when it's saved.
- the endpoint is /update/ by default, but can be changed with the `rkv_remote_repo_endpoint` filter
- as it stands now, the repo doesn't have any front-end display templates, but there shouldn't be anything preventing it from being front-end accessible

**Comment by jamesckemp** [comment]
Ah, thanks - I think I get it now!

I didn't realise there's essentially two parts to this:
- Setup a wordpress site and install the core plugin - giving me access to a custom post type where I can configure my plugins.
- Include the class in the "sample-plugin" folder, and the code in my plugin class.

Will give it a whirl - thanks!

**Comment by norcross** [comment]
you got it. this is meant to be on an install that other sites access. lemme know how it goes!
